name: building-height
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gdal=3.5
  - rasterio=1.3
  - shapely=1.8
  - affine=2.3
  - numpy=1.23
  - pandas=1.4
  - geopandas=0.12
  - rasterstats=0.17